version: '3'
services:
  app:
    build: .
      # dockerfile: Dockerfile
    container_name: 'probspace'
    devices:
      - /dev/nvidia0
    working_dir: '/workspace'
    volumes:
      - ./:/workspace/
    ports:
      - "127.0.0.1:8081:8888"
    tty: true
      
